spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.23.143.189:3306/cloudstudy?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234567
